name: capstone_d2
channels:
  - defaults
  - conda-forge
dependencies:
  - aiofiles=22.1.0=py310haa95532_0
  - aiohappyeyeballs=2.4.4=py310haa95532_0
  - aiohttp=3.11.10=py310h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py310haa95532_0
  - anyio=4.6.2=py310haa95532_0
  - async-timeout=4.0.3=py310haa95532_0
  - attrs=24.3.0=py310haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli-python=1.0.9=py310h5da7b33_9
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - cairo=1.16.0=hc68a040_5
  - certifi=2024.12.14=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310haa95532_0
  - cloudpickle=3.0.0=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - cryptography=43.0.3=py310hbd6ee87_1
  - dataclasses-json=0.6.5=py310haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - distro=1.9.0=py310haa95532_0
  - dnspython=2.4.2=py310haa95532_0
  - dotnet=7.0.102=h57928b3_0
  - dotnet-aspnetcore=7.0.2=h91493d7_0
  - dotnet-desktop=7.0.2=h57928b3_0
  - dotnet-runtime=7.0.2=h91493d7_0
  - dotnet-sdk=7.0.102=h91493d7_0
  - editdistance=0.8.1=py310h5da7b33_0
  - email-validator=2.2.0=pyhd8ed1ab_1
  - email_validator=2.2.0=hd8ed1ab_1
  - exceptiongroup=1.2.0=py310haa95532_0
  - expat=2.6.4=h8ddb27b_0
  - fastapi=0.115.6=pyhd8ed1ab_0
  - fastapi-cli=0.0.7=pyhd8ed1ab_0
  - ffmpeg=6.1.1=hfbd6584_1
  - ffmpy=0.3.0=pyhb6f538c_0
  - filelock=3.13.1=py310haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.5.0=py310h827c3e9_0
  - fsspec=2024.12.0=py310haa95532_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gradio=5.12.0=pyhd8ed1ab_0
  - gradio-client=1.5.4=pyhd8ed1ab_0
  - graphite2=1.3.14=hd77b12b_1
  - greenlet=3.1.1=py310h5da7b33_0
  - h11=0.14.0=py310haa95532_0
  - harfbuzz=4.3.0=hb646838_2
  - httpcore=1.0.2=py310haa95532_0
  - httptools=0.6.4=py310h827c3e9_0
  - httpx=0.27.0=py310haa95532_0
  - httpx-sse=0.4.0=py310haa95532_0
  - huggingface_hub=0.27.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py310haa95532_1
  - jiter=0.6.1=py310hefb1915_0
  - joblib=1.4.2=py310haa95532_0
  - jpeg=9e=h827c3e9_3
  - jsonpatch=1.33=py310haa95532_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - langchain-openai=0.2.14=pyhd8ed1ab_0
  - langchain-text-splitters=0.3.3=py310haa95532_0
  - langsmith=0.1.147=py310haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h5da7b33_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libtheora=1.1.1=h8cc25b3_3
  - libtiff=4.5.1=h44ae7cf_1
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.5=h24da03e_0
  - llvmlite=0.43.0=py310hf2fb9eb_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=2.2.0=py310haa95532_1
  - markupsafe=2.1.3=py310h827c3e9_1
  - marshmallow=3.19.0=py310haa95532_0
  - mdurl=0.1.0=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - multidict=6.1.0=py310h827c3e9_0
  - mypy_extensions=1.0.0=py310haa95532_0
  - numba=0.60.0=py310h5da7b33_0
  - numexpr=2.10.1=py310h4cd664f_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - openai=1.52.1=py310haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.15=h827c3e9_0
  - orjson=3.10.14=py310h636fa0f_0
  - packaging=24.2=py310haa95532_0
  - pandas=2.2.3=py310h5da7b33_0
  - pandasql=0.7.3=py310haa95532_1
  - pcre2=10.42=h0ff8eda_1
  - pickles=4.0.3=h267e887_1
  - pillow=11.0.0=py310h096bfcc_1
  - pip=24.2=py310haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - propcache=0.2.0=py310h827c3e9_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py310haa95532_0
  - pydantic-core=2.27.1=py310h636fa0f_0
  - pydantic-settings=2.6.1=py310haa95532_0
  - pydub=0.25.1=pyhd8ed1ab_1
  - pygments=2.15.1=py310haa95532_1
  - pypickle=1.1.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py310haa95532_0
  - pysqlite3=0.5.4=py313hb2a9d6d_0
  - python=3.10.16=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-dotenv=0.21.0=py310haa95532_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310haa95532_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - regex=2024.11.6=py310h827c3e9_0
  - requests=2.32.3=py310haa95532_1
  - requests-toolbelt=1.0.0=py310haa95532_0
  - rich=13.9.4=py310haa95532_0
  - rich-toolkit=0.11.3=pyh29332c3_0
  - ruff=0.9.1=py310h8ecf97c_0
  - safehttpx=0.1.6=pyhd8ed1ab_1
  - scikit-learn=1.2.2=py310hd77b12b_1
  - scipy=1.15.1=py310h8640f81_0
  - semantic_version=2.8.5=pyhd3eb1b0_0
  - setuptools=75.1.0=py310haa95532_0
  - shap=0.46.0=py310hc64d2fc_0
  - shellingham=1.5.0=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.8=py310h9909e9c_0
  - sniffio=1.3.0=py310haa95532_0
  - sqlalchemy=2.0.37=py310h54f65d0_0
  - sqlite=3.45.3=h2bbff1b_0
  - starlette=0.41.3=pyha770c72_1
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=9.0.0=py310haa95532_0
  - threadpoolctl=3.5.0=py310h9909e9c_0
  - tiktoken=0.8.0=py310hddca29c_1
  - tk=8.6.14=h0416ee5_0
  - tomlkit=0.13.2=py310haa95532_0
  - tqdm=4.66.5=py310h9909e9c_0
  - typer=0.15.1=pyhd8ed1ab_0
  - typer-slim=0.15.1=pyhd8ed1ab_0
  - typer-slim-standard=0.15.1=hd8ed1ab_0
  - typing-extensions=4.12.2=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - typing_inspect=0.9.0=py310haa95532_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - urllib3=2.3.0=py310haa95532_0
  - uvicorn=0.32.1=py310haa95532_0
  - uvicorn-standard=0.32.1=py310haa95532_0
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - watchfiles=0.24.0=py310h636fa0f_2
  - websockets=10.4=py310h827c3e9_2
  - wheel=0.44.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py310h827c3e9_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - langchain==0.3.14
      - langchain-community==0.3.14
      - langchain-core==0.3.30
prefix: C:\Users\rishinair\AppData\Local\anaconda3\envs\capstone_d2
